# Build-time test discovery for a Unity runner.
#
# Runs the freshly-linked runner with `-l`, which makes Unity print the tests it
# was generated with, and writes a CTest include file registering one CTest
# entry per Unity test. Because this runs after every link, the CTest list can
# never drift from the runner's contents: adding, renaming or commenting out a
# test is picked up on the next build with no `cmake` re-run.
#
# Expects: TEST_EXECUTABLE, TEST_PREFIX, CTEST_FILE

execute_process(
    COMMAND "${TEST_EXECUTABLE}" -l
    OUTPUT_VARIABLE listing
    ERROR_VARIABLE  listing_err
    RESULT_VARIABLE listing_rc
)

if(NOT listing_rc EQUAL 0)
    message(FATAL_ERROR
        "Could not list tests in ${TEST_EXECUTABLE} (exit ${listing_rc}).\n"
        "Was the runner generated with --cmdline_args=1 and built with "
        "UNITY_USE_COMMAND_LINE_ARGS?\n${listing}${listing_err}")
endif()

# `-l` prints the suite filename flush left, then each test indented by two
# spaces. Match on the indent so the filename line is not mistaken for a test.
string(REPLACE "\n" ";" listing_lines "${listing}")

set(ctest_content "")
set(found 0)
foreach(line IN LISTS listing_lines)
    if(line MATCHES "^[ \t]+([A-Za-z_][A-Za-z0-9_]*)[ \t]*$")
        set(test_name "${CMAKE_MATCH_1}")
        # A CTest include file only understands the legacy positional
        # add_test(<name> <command> <args>...) form; the add_test(NAME ...
        # COMMAND ...) keyword form silently names every test "NAME".
        string(APPEND ctest_content
            "add_test(\"${TEST_PREFIX}${test_name}\""
            " \"${TEST_EXECUTABLE}\" -n \"${test_name}\")\n")
        # Unity exits 0 for an ignored test, which CTest would otherwise
        # report as a pass. Surface them as skips instead.
        string(APPEND ctest_content
            "set_tests_properties(\"${TEST_PREFIX}${test_name}\""
            " PROPERTIES SKIP_REGULAR_EXPRESSION \":IGNORE\")\n")
        math(EXPR found "${found} + 1")
    endif()
endforeach()

if(found EQUAL 0)
    message(FATAL_ERROR "No tests found in ${TEST_EXECUTABLE}. Output was:\n${listing}")
endif()

file(WRITE "${CTEST_FILE}" "# Generated by DiscoverUnityTests.cmake -- do not edit.\n${ctest_content}")
