# Build-time script: write a header defining ARGUS_GIT_VERSION as the current
# git hash, with "-dirty" appended if the tree has uncommitted or untracked
# changes. The file is only rewritten when the version changes, so it doesn't
# force a recompile on every build.
# Expects: SRC_DIR, OUT_FILE

execute_process(
        COMMAND git rev-parse --short=8 HEAD
        WORKING_DIRECTORY ${SRC_DIR}
        OUTPUT_VARIABLE GIT_HASH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE GIT_RESULT
)
if(NOT GIT_RESULT EQUAL 0 OR GIT_HASH STREQUAL "")
        set(GIT_HASH "unknown")
else()
        # --porcelain also catches untracked files, unlike `git describe --dirty`.
        execute_process(
                COMMAND git status --porcelain
                WORKING_DIRECTORY ${SRC_DIR}
                OUTPUT_VARIABLE GIT_STATUS
        )
        if(NOT GIT_STATUS STREQUAL "")
                string(APPEND GIT_HASH "-dirty")
        endif()
endif()

set(CONTENT "/* Generated by cmake/gen_version.cmake. Do not edit. */\n#pragma once\n\n#define ARGUS_GIT_VERSION \"${GIT_HASH}\"\n")

if(EXISTS ${OUT_FILE})
        file(READ ${OUT_FILE} OLD_CONTENT)
endif()
if(NOT CONTENT STREQUAL OLD_CONTENT)
        file(WRITE ${OUT_FILE} "${CONTENT}")
endif()
